#+TITLE: ミームの臭い
#+DATE: 2020-12-12
#+AUTHOR: まんじゅ（´ん｀）
#+EMAIL: manzyun@gmail.com

実際のセッションでは新クトゥルフ TRPG(CoC7th)で運用したが、
技能値において特殊な判定を必要としないシナリオのため 6 版でのセッションも可能と思われる。

なお難易度は、「新規探索者」でセッション時間はオンライン(ボイスチャットと支援ツール併用)で 4 時間である。

また、このセッションでは「ソフトウェア開発(特に『フリーソフトウェア』『オープンソース』『インターネットプロトコル』)」における
固有名詞ないし用語が頻繁に出るため、キーバーはその分野に明るい方が運用しやすいかもしれない事も付け加える。

加えて、上記の様な事項や、筆者独自の思想や考えについても書き記すため、このシナリオには脚注情報が多い事を断らせて頂く。


* シナリオ概要
昨今世間を賑わせている VTuber[fn:1] 界隈であるが、そこに新たな新星『[[*夢持 黄昏(ゆめもち たそがれ) 、さりげ無く知性を漂わせる VTuber][夢持 黄昏(ゆめもち たそがれ)]]』が現われる。
その同時期に、インターネットの噂共有サイトや匿名掲示板では「怪奇!! パソコンの前から突如人が消える事件が多発」
というタレコミが散見される。

探索者達はひょんなことからこの事件、そしてとある企業の陰謀とその打破に巻き込まれる。

** 推奨技能
<コンピューター> <電子工作>を推奨。

また、ここに記している内容のみであれば、戦闘は無いシナリオである。

「インターネットでの検索エンジンによる情報探索」も高頻度で発生するシナリオなので、
<図書館> による代用ないし併用ロールを KP は受け付ける事を推奨する。

「インターネットでの検索エンジンによる情報探索」においては、
実際にプレイヤーから「問い合わせの際に使用するキーワードや検索条件」を提案してもらい、
プレイヤーキャラクターがそのキーワードを思い付くかロールしてもらう方が現実味があって面白いと筆者は思い抱く。

* キーパー向け情報
夢持 黄昏は後述する『[[*バベッジ・インコーポレイテッド][バベッジ・インコーポレイテッド]]』の子会社『バベッジ・インコーポレイティッド アブストラクトメディア・ラボ』社
が企画した VTuber であり、表向きの活動は、 \
「『バベッジ・インコーポレイテッド アブストラクトメディア・ラボ』社の開発したゲームソフトの宣伝・販売促進や、同社が行うイベントの広報」 \
であるが裏の活動目的として、 \
「更なるミームの流動促進による 『[[*ADA マークアップ言語][ADA]]』 や 『[[*Intelligent Difference Engine v2.0 (IDE2.0) プロトコル][IDE2.0]]』 上の偶発的な呪文発生の可能性の向上、そしてその呪文を元にセラノエの大図書館を含む情報へのアクセス方法を導き、ひいては人類の進化を目指す」 \
というものがある。

しかしながら、偶発による呪文の発生とその実行による _事故_ として、夢持 黄昏の配信やそのアーカイブを視聴している者達が、
パソコンの前から電子世界(主に夢持の存在を感じられる世界)へと移送(転送)されるという事象が多発する様になった。

この事態を危惧したある『ホワイトハッカー集団』がこの事態への早急な対処を試み、
「IDE2.0 プロトコル内のある値の削除や、その演算や実行を抑止する」
コンピューターウィルスを開発した。

しかし、このコンピューターウィルスはまだ強い伝搬能力を持っておらず、バベッジ・インコーポレイテッド製のセキュリティソフトによって、
容易に無効化されてしまう。

また、事故が多発しているのは日本であり



-----

このシナリオは参考資料に上げている通り、『クトゥルフカルト・ナウ』の『バベッジ・イン・コーポレイテッド』の情報を元に作成したシナリオである。
その為、詳細(例えば「企業理念」や「活動背景」と言った言外の意図)を知りたい方は、同サプリメントの購入をお勧めする。

以下では、同サプリメントの内容から掻い摘みかつ雑に、このシナリオを進行するに当たっての重要な情報の説明のみに留める。

** バベッジ・インコーポレイテッド
ありとあらゆる情報通信媒体の通信部分を担う企業。パーソナルコンピューターの開発も行なっており、プレイヤーキャラクター達の住む世界では
街中に同社の製品が溢れているだろう。

** ADA マークアップ言語
Web サイトを見回ってているだけだと馴染みが無いが、Web サイトの文書などの殆どはマークアップ言語で書かれている。

ADA(エイダ)はバベッジ・インコーポレイテッドの開発した、Web サイトの文書の構造定義やその文書の装飾から、
他のプログラムやソフトウェアで利用可能なデータ構造とその内容を定義する事のできるマークアップ言語である。

要は「XML の様なもののバベッジ・イン・コーポレイテッドによる別の実装」と踏まえておけば、プログラマなどには伝わるのかもしれない。

** Intelligent Difference Engine v2.0 (IDE2.0) プロトコル
バベッジ・インコーポレイテッドの提唱した独自ネットワークプロトコルである。

ネットワークプロトコルについて、コンピューターネットワークについて明るくない方に向けて説明すると、 \
「コンピューター間で行われる通信上でやりとりされるデータの形式」 \
と踏まえて頂ければ良い。

なお、このプロトコルとそれらを処理するプロセッサについてはサプリメント内で、

#+begin_quote
従来型のルーターの数十倍の通信速度を、安価・小型に実現したため、企業のセンター・ルーターのうちかなりのものが、
現在バベッジ・インコーポレイテッドのものに置き換えられている。
#+end_quote

と記されているので、このプロトコルの提唱やそれを処理するプロセッサの開発によって、バベッジ・インコーポレイテッドは
プレイヤーキャラクター達の世界中のコンピューターネットワークを手中に収めているだろう。

なお、実際の我々の世界でも「[[https://wa3.i-3-i.info/word12853.html][IDE(Integrated Drive Electronics)]]」という補助記録装置との古い接続規格があったり、
ソフトウェア開発においては「[[https://wa3.i-3-i.info/word2590.html][統合開発環境(Integrated Development Environment)]]」を指すので、
キーパー・プレイヤー共々、混同してしまわない様に注意されたい。


** 余談 :: 筆者独自の思い描くバベッジ・インコーポレイテッドの製品の優位性について
表立って述べれば、[[*ADA マークアップ言語][ADA]] が我々の世界での XML などと比べて特筆する点は、 \
「Web ブラウザで文書が表示されるまでの速度が数桁倍早い」 \
事だろう。

その要因は『[[*Intelligent Difference Engine v2.0 (IDE2.0) プロトコル][IDE2.0]]』と組み合っての「転送処理の高速な圧縮や最適化と、その上での高速な転送速度」、
その上で「高速な Web ブラウザソフトでの文書描画速度」と想像する。

*** プログラマやアーキテクトデザイナ向けのもっとコアな空想
[[*バベッジ・インコーポレイテッド][バベッジ・インコーポレイテッド]]のプロセッサ群は、同社の開発した言語やプロトコルの最適化と圧縮、そして別言語への変換も、
読者含む我々が想像できないくらい容易に高速で行う。

その為、エンドユーザー(つまり、Web サイト文書閲覧者)が、ブラウザの『開発者ツール』ないし『デベロッパーツール』を使用して、
閲覧している文書のソースコードを読んでも、そこにはごく普通の HTML, CSS, JavaScript のソースコードが表示されるだろうし、
開発者ツールの『ネットワーク分析』ツールを使用しても、ごく普通の HTTP(S)のやり取りしか見受けられない。

筆者個人の知見と想像力では、 \
「シナリオに組み込むにあたってのバベッジ・インコーポレイテッドが行っている *偽装* はこれくらいの塩梅だろう(そうしないと、手掛りが掴めない)」 \
と妥協した。なので現実ではもっと偽装したやりとりが在るのかもしれない。

この筆者の空想を絡めてセッション中に出す情報として以下を追加すると、少し現実味が増すかもしれない。

- バベッジ・インコーポレイテッドと、『[[https://wa3.i-3-i.info/word1950.html][W3C]]』等の標準化団体との関係
  - 独自プロトコルと独自マークアップ言語の使用とその仕様の公開についてはごく一部で、それ以上は完全に非協力的であること
- 個人 Web サーバーやサービスでは、『ADA』や『IDE2.0』を利用したサービスと比較すると圧倒的に動作や描画が遅い事


* NPC 情報
** 夢持 黄昏(ゆめもち たそがれ)、  さりげ無く知性を漂わせる VTuber 

- APP
  - VTuber 時の状態
    + <= 6th :: 17
    + 7th :: 88
- SIZ
  - VTuber 時の状態
    + <= 6th :: 12
    + 7th :: 60
    
/あくまでこれらのステータス数値は『VTuber』の姿の時のものである。/
/シナリオの進行によっては他のステータス値を当てるなり、/
/変化して異界の生き物の姿に(APP を最低値にする)する等、自由に行って構わない。/

/もしかすると、夢持と対峙する時にはプレイヤーキャラクターは『電子』の世界に居るかもしれないし、/
/夢持が『現世に肉体を投影』している時と思うが。/


VTuber (3D モデル)の容姿は、黄色いパーカーを被った亜麻色で赤い瞳をしている、小麦色の肌の女の子である。
年齢は 16 歳前後という設定の印象を受ける。

主に『[[*バベッジ・インコーポレイテッド][バベッジ・インコーポレイテッド]]』の子会社『バベッジ・インコーポレイティッド アブストラクトメディア・ラボ』社の
開発したテレビゲームや PC ゲームの先行ゲーム実況を行っているが、雑談では哲学や宇宙、科学技術の話も折り混ぜるという知的側面も彼女の人気の要因の一つかもしれない。

*** 余談 :: 筆者の思い考える彼女の能力
彼女はまさに『偶像』の意味の『アイドル』である。その為、特別な技能や魔力は持ち合わせていないと考える。

ただしあくまで上記は筆者個人の考えなので、彼女自身に特殊な能力を与えたいというキーバーが居るならば、筆者は拒否するつもりは無い。

参考になるかは定かでは無いが、彼女が持ち合わせそうな呪文をいくつか挙げる。キーパーは下記の呪文を必要に応じて追加・削除を行っても良いだろう。
また、判定の際の材料として、彼女の POW は 以下と定義する。

- <= 6th :: 20 以上
- 7th :: 140 以上

----
  
- 電子の誘惑的な舌(「犠牲者を魅了する」) :: 対象者と穏やかに対話できる環境で、対象との POW ロールを行う。
  成功した場合、犠牲者は 1D6 ラウンドの間、行動・発言などができなくなる。なお、犠牲者は叩き起こして正気に戻す事ができる。
- 電子の無感覚なゴーストの囁き(「支配」) :: 対象の意志をねじ曲げて、術者の意志どおりにさせる事ができる。
  ただし、この呪文は対象が *インターネット回線に接続している何らかの通信媒体* から *文書や音声や映像等の情報を得ている状態* にしかこの呪文の判定はできず、
  対象との POW ロールに成功しなければならない。また、対象の基本的な性質に反する命令(羽や浮遊能力の無い人類に「飛べ。はばたけ」という様なもの)も中断されるだろう。
- ミームの依存性注入(「恐怖の注入」) :: 瞬時に判定無しで対象を 0/1D6 正気度を失なわせる事ができる。ただし、対象が
  *インターネット回線に接続している何らかの通信媒体* から *文書や音声や映像等の情報を得ている状態* にしかこの呪文は発動しない。
- ミームの流れへの同化 :: *インターネット回線に接続している何らかの通信媒体* を媒介として、術者自身の身体を転移する呪文。
  フレーバーとして、通信状況や電波状況の悪い所からの転移や、同状況への転移には時間を要するというのも一興と筆者は考える。

  
** 夢持 黄昏のファン、ミームの海に漂う宿命の被害者達


  
* 参考資料
- サプリメント :: ログインテーブルトーク RPG シリーズ「クトゥルフ神話 TRPG 『クトゥルフカルト・ナウ』」

* 影響を受けた作品
- [[https://store.steampowered.com/app/365450/Hacknet/][Hacknet]]


* 謝辞
前日に A4 コピー用紙に殴り書きした「シナリオ進行のグラフ図」でしか無かったこのシナリオの実質テストプレイに
お付き合い頂いた、『Qiitadon アナログゲーム部』の「えだ」氏と「よっしー」氏に、感謝申し上げる。

また、『バベッジ・インコーポレイテッド』という、筆者の興味に深く刺さるカルト企業を、
『クトゥルフカルトナウ』に記して下さった松本寛大様や、他同著の制作に携わった皆々様に感謝をこの場で申し上げる。


* Footnotes

[fn:1] Virtual Youtuber を縮めてこの様に書く。主にゲームプレイ動画や雑談を、二次元イラストアニメーションや 3D モデルを介して配信している。
